spring.application.name=ShlopApp

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=SHOE_STORE_APP
spring.datasource.password=my_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


spring.data.redis.host=localhost
spring.data.redis.port=6379